# Generated by Django 5.1.2 on 2025-02-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosEconomicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(unique=True)),
                ('janeiro', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fevereiro', models.DecimalField(decimal_places=2, max_digits=5)),
                ('março', models.DecimalField(decimal_places=2, max_digits=5)),
                ('abril', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('junho', models.DecimalField(decimal_places=2, max_digits=5)),
                ('julho', models.DecimalField(decimal_places=2, max_digits=5)),
                ('agosto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('setembro', models.DecimalField(decimal_places=2, max_digits=5)),
                ('outubro', models.DecimalField(decimal_places=2, max_digits=5)),
                ('novembro', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dezembro', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
